### PR TITLE
fix: add XGoogFieldMask constant

### LINKED ISSUE #320: callctx: consider adding x-goog-fieldmask constant or helper
We should consider adding something to help users with the sending Google system parameters, specifically the FieldMask.

Note: [gRPC requires that the headers be lower case](https://cloud.google.com/apis/docs/system-parameters#grpc_mapping), so any use of the actual value should be lower case, since HTTP headers are case insensitive.

Some ideas:
* a constant like `const XGoogFieldMask = "x-goog-fieldmask`
* a helper like `func SetFieldMask(ctx context.Context, fields ...string) context.Context`
* a helper like `func SetFieldMask(ctx context.Context, mask fieldmaskpb.FieldMask) context.Context` (using [fieldmaskpb](https://pkg.go.dev/google.golang.org/protobuf/types/known/fieldmaskpb))
* A mix or all of the above

Motivation: https://github.com/googleapis/google-cloud-go/issues/9303

### PR DESCRIPTION
**Pull request by noahdietz**
Adds `XGoogFieldMask` constant for use with `SetHeaders` to supply the Google API system parameter.

Include documentation "redirect" to `callctx` for `BuildHeaders` and other internal header related helpers in the top level package.

Add example snippets for `XGoogFieldMask`.

Fixes #320 - we will only do this constant for now.

### CODE REVIEW

**Review by quartzmo — APPROVED** [review]
LGTM

File: v2/callctx/callctx.go [hunk 1]
```diff
@@ -38,6 +38,14 @@ import (
 )
 
 const (
+	// XGoogFieldMask is the canonical header key for the [System Parameter]
+	// that specifies the response read mask. The value(s) for this header
+	// must adhere to format described in [fieldmaskpb].
+	//
+	// [System Parameter]: https://cloud.google.com/apis/docs/system-parameters
+	// [fieldmaskpb]: https://google.golang.org/protobuf/types/known/fieldmaskpb
+	XGoogFieldMask = "x-goog-fieldmask"
```
Comment (codyoss) [inline v2/callctx/callctx.go:47]: nit: should this have the word Header or Key in the name? I am just thinking if we add more of these in the future it would be nice to have a grouping of them

Comment (noahdietz) [reply v2/callctx/callctx.go]: Sure thing, added the `Header` suffix to the name.

**Review by codyoss — APPROVED** [review]
